# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
version: 2
project_name: tillandsia

before:
  hooks:
    - go mod tidy

builds:
  - id: tillandsia
    binary: tillandsia
    main: ./cmd/tillandsia
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64

  - id: tillandsia-init
    binary: tillandsia-init
    main: ./cmd/tillandsia-init
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm64

archives:
  - formats: tar.gz
    files:
      - README.md

checksum:
  name_template: "checksums.txt"

snapshot:
  name_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"